### ISSUE TITLE
Plusieurs moyens d'accéder au backend

### ISSUE THREAD

**Issue by sebastienD** [Zenika/angular-aws-tz-bdx-2024#5]
Serait-il possible d'avoir plusieurs routes Angular.

Une qui pointe sur des données statiques. L'uri du backend serait "/boardgames/static".

Et une autre qui pointe sur des données qui vont être récupérées en BDD. L'uri du backend serait "/boardgames".

**Comment by aceol** [comment]
on a maintenant 2 urls: 
`/static`
et `/dynamic`
